#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Jun 06, 2019 01:29:18 AM


import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

from tkFileDialog import askopenfilename
from tkFileDialog import askdirectory

def set_Tk_var():
    global editText
    editText = StringVar()
    global FilePath
    FilePath = StringVar()
    FilePath.set("LOAD FILE")
    global Directory
    Directory = StringVar()
    Directory.set("LOAD PATH")

def LoadDirectory():
    print('BasicTutorial_support.LoadDirectory')
    Directory.set(askdirectory())
    sys.stdout.flush()

def LoadFilePath():
    print('BasicTutorial_support.LoadFilePath')
    FilePath.set(askopenfilename(title="LOAD FILE"))
    sys.stdout.flush()

def SimpleFunction(number):
    print('BasicTutorial_support.SimpleFunction')
    editText.set(Directory.get() + str(number) + ".json")
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import BasicTutorial
    BasicTutorial.vp_start_gui()


